### ISSUE TITLE
Library is not created for Register Repository (after upgrade)

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#337]
Testing scenario:

clone zebrunner from master, setup everything and run regression jobs
switched to develop branch and do recurive pull
execute upgrade task
./zebrunner.sh upgrade
restart everything
Recreate Organization
Actual result: Library is not created for Register Repository

Resume disabled by user, switching to high-performance, low-durability mode.
ERROR: Could not find any definition of libraries [Zebrunner-CE@1.1]
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: Loading libraries failed
1 error
	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:571)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:523)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:337)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Finished: FAILURE

**Comment by vdelendik** [comment]
fixed. during the upgrade it should ask about custom global pipeline libraries. Answer "n" if you didn't register any custom global pipeline. As result qps-pipeline will be replaced by new Zebrunner-CE

**Comment by okamara** [comment]
Tested . Fixed.
