### ISSUE TITLE
reporting can't be started after upgrade to 1.2: function update_modified_at() does not exist

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#347]
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-11-05 13:58:43.326 ERROR [zafira] [main] o.s.boot.SpringApplication: Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'integrationStorage' defined in URL [jar:file:/app/reporting-service.jar!/BOOT-INF/classes!/com/zebrunner/reporting/service/integration/core/IntegrationStorage.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tenantService' defined in class path resource [com/zebrunner/common/mt/service/ServiceAutoConfiguration.class]: Unsatisfied dependency expressed through method 'tenantService' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tenantRepository': Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set classpath:db/changelog.yml::008_create_active_projects_table::nsidorevich:
     Reason: liquibase.exception.DatabaseException: ERROR: function update_modified_at() does not exist [Failed SQL: (0) CREATE TABLE IF NOT EXISTS active_projects (
  id SERIAL,
  name VARCHAR(255) NOT NULL,
  key VARCHAR(10) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  modified_at TIMESTAMP NOT NULL,
  deleted BOOL DEFAULT false,
  PRIMARY KEY (id),
  UNIQUE (key),
  UNIQUE (name)
);
CREATE TRIGGER update_timestamp_active_projects
BEFORE INSERT OR UPDATE ON active_projects FOR EACH ROW
EXECUTE PROCEDURE update_modified_at()]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:797)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:227)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at com.zebrunner.reporting.ApplicationInitializer.main(ApplicationInitializer.java:12)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tenantService' defined in class path resource [com/zebrunner/common/mt/service/ServiceAutoConfiguration.class]: Unsatisfied dependency expressed through method 'tenantService' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tenantRepository': Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set classpath:db/changelog.yml::008_create_active_projects_table::nsidorevich:
     Reason: liquibase.exception.DatabaseException: ERROR: function update_modified_at() does not exist [Failed SQL: (0) CREATE TABLE IF NOT EXISTS active_projects (
  id SERIAL,
  name VARCHAR(255) NOT NULL,
  key VARCHAR(10) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  modified_at TIMESTAMP NOT NULL,
  deleted BOOL DEFAULT false,
  PRIMARY KEY (id),
  UNIQUE (key),
  UNIQUE (name)
);
...
```

**Comment by vdelendik** [comment]
done: hotfix 347.sh added to repo and migration steps updated
