### ISSUE TITLE
Test run reports from Launcher are not visible 

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#389]
Steps:
1. Start jenkins and reporting
2. Create organization and repo in jenkins
3. Open Launcher and run Api job
4. Actual result: job is started but job result is not visible

<img width="918" alt="Screen Shot 2021-01-22 at 7 00 35 PM" src="https://user-images.githubusercontent.com/32964663/105514365-76c73e00-5ce4-11eb-8864-88aab000c62c.png">

Log:
2021-01-22 15:57:32.689 DEBUG [http-nio-8080-exec-9] c.z.c.e.w.t.a.BaseApplicationExceptionTranslator: Test run for CI run id 'bef463d6-7e5f-4479-a326-bc3655674649' can not be found
com.zebrunner.common.eh.exception.ResourceNotFoundException: 2037 - TEST_RUN_NOT_FOUND_BY_CI_RUN_ID - [bef463d6-7e5f-4479-a326-bc3655674649]
	at com.zebrunner.reporting.service.TestRunService.lambda$getTestRunByCiRunId$1(TestRunService.java:144)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at com.zebrunner.reporting.service.TestRunService.getTestRunByCiRunId(TestRunService.java:144)
	at com.zebrunner.reporting.service.TestRunService$$FastClassBySpringCGLIB$$a459ab29.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at com.zebrunner.reporting.service.TestRunService$$EnhancerBySpringCGLIB$$af83cd27.getTestRunByCiRunId(<generated>)
	at com.zebrunner.reporting.web.TestRunController.getTestRunByCiRunId(TestRunController.java:195)
	at com.zebrunner.reporting.web.TestRunController$$FastClassBySpringCGLIB$$9bafab87.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at com.zebrunner.reporting.web.TestRunController$$EnhancerBySpringCGLIB$$362d1331.getTestRunByCiRunId(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.spr

////
2021-01-22 15:57:11.490 DEBUG [http-nio-8080-exec-6] c.z.c.e.w.t.a.BaseApplicationExceptionTranslator: Test run for CI run id 'bef463d6-7e5f-4479-a326-bc3655674649' can not be found
com.zebrunner.common.eh.exception.ResourceNotFoundException: 2037 - TEST_RUN_NOT_FOUND_BY_CI_RUN_ID - [bef463d6-7e5f-4479-a326-bc3655674649]
	at com.zebrunner.reporting.service.TestRunService.lambda$getTestRunByCiRunId$1(TestRunService.java:144)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at com.zebrunner.reporting.service.TestRunService.getTestRunByCiRunId(TestRunService.java:144)
	at com.zebrunner.reporting.service.TestRunService$$FastClassBySpringCGLIB$$a459ab29.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at com.zebrunner.reporting.service.TestRunService$$EnhancerBySpringCGLIB$$af83cd27.getTestRunByCiRunId(<generated>)
	at com.zebrunner.reporting.web.TestRunController.getTestRunByCiRunId(TestRunController.java:195)
	at com.zebrunner.reporting.web.TestRunController$$FastClassBySpringCGLIB$$9bafab87.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at com.zebrunner.reporting.web.TestRunController$$EnhancerBySpringCGLIB$$362d1331.getTestRunByCiRunId(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web

**Comment by vdelendik** [comment]
closing as can't repro

**Comment by okamara** [comment]
Repro on develop and master branch 

Log:
[ERROR] java.lang.NullPointerException: Cannot invoke method equalsIgnoreCase() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at com.zebrunner.jenkins.pipeline.runner.maven.TestNG.addProviderCapabilities(TestNG.groovy:936)
	at com.zebrunner.jenkins.pipeline.runner.maven.TestNG.getMavenGoals(TestNG.groovy:845)
	at com.zebrunner.jenkins.pipeline.runner.maven.TestNG.buildJob(TestNG.groovy:733)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor157.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by vdelendik** [comment]
fixed. hotfix applied for 1.4 via pipeline and jenkins-master

**Comment by okamara** [comment]
Verified.
