### ISSUE TITLE
Mail service doesn't work .Failed to process message MailDataMessage.

### ISSUE THREAD

**Issue by dhreben** [zebrunner/zebrunner#403]
**Test scenario:**

1.git clone --recurse-submodule --branch develop https://github.com/zebrunner/zebrunner.git
2.Run ./zebrunner.sh setup and enter:
SMTP host :
port :
user:
email:
password:
3.Open Jenkins
4.Run RegisterOrganization
5.Run RegisterRepository
6.Run API-Demo-Test and enter your email to email_list
7.Tab build
8. Enter  on terminal docker logs mail-service

**Actual result**:  Mail service doesn't work.Failed to process message MailDataMessage

ui: 1.20.1.RC1
server: 1.20.1.RC2

```
2021-02-04 19:47:17.979 ERROR 1 --- [ntContainer#0-3] c.z.m.m.listener.MailMessageListener     : Failed to process message MailDataMessage(toEmails=[dhreben@solvd.com], subject=PASSED: Carina Demo Tests - API Sample)

com.zebrunner.ms.service.exception.ServiceException: Error processing template
	at com.zebrunner.ms.service.impl.TemplateServiceImpl.processIntoHtml(TemplateServiceImpl.java:59) ~[classes!/:na]
	at com.zebrunner.ms.service.impl.TemplateServiceImpl.loadAndProcess(TemplateServiceImpl.java:44) ~[classes!/:na]
	at com.zebrunner.ms.service.impl.MailServiceImpl.processAndSend(MailServiceImpl.java:60) ~[classes!/:na]
	at com.zebrunner.ms.messaging.listener.MailMessageListener.processMailMessage(MailMessageListener.java:24) ~[classes!/:na]
	at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) ~[spring-messaging-5.3.1.jar!/:5.3.1]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) ~[spring-messaging-5.3.1.jar!/:5.3.1]
	at org.springframework.amqp.rabbit.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:53) ~[spring-rabbit-2.3.1.jar!/:2.3.1]
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:220) ~[spring-rabbit-2.3.1.jar!/:2.3.1]
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandlerAndProcessResult(MessagingMessageListenerAdapter.java:148) ~[spring-rabbit-2.3.1.jar!/:2.3.1]
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:133) ~[spring-rabbit-2.3.1.jar!/:2.3.1]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1632) ~[spring-rabbit-2.3.1.jar!/:2.3.1]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1551) ~[spring-rabbit-2.3.1.jar!/:2.3.1]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1539) ~[spring-rabbit-2.3.1.jar!/:2.3.1]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1530) ~[spring-rabbit-2.3.1.jar!/:2.3.1]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1474) ~[spring-rabbit-2.3.1.jar!/:2.3.1]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:966) ~[spring-rabbit-2.3.1.jar!/:2.3.1]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:912) ~[spring-rabbit-2.3.1.jar!/:2.3.1]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:83) ~[spring-rabbit-2.3.1.jar!/:2.3.1]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1287) ~[spring-rabbit-2.3.1.jar!/:2.3.1]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1193) ~[spring-rabbit-2.3.1.jar!/:2.3.1]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> testRun.queued  [in template "62de5038-930d-4e14-b78a-bcf190fcf1e5" at line 76, column 27]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #if (testRun.queued > 0)  [in template "62de5038-930d-4e14-b78a-bcf190fcf1e5" at line 76, column 21]
----
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134) ~[freemarker-2.3.30.jar!/:2.3.30]
	at freemarker.core.EvalUtil.compare(EvalUtil.java:198) ~[freemarker-2.3.30.jar!/:2.3.30]
	at freemarker.core.EvalUtil.compare(EvalUtil.java:115) ~[freemarker-2.3.30.jar!/:2.3.30]
	at freemarker.core.ComparisonExpression.evalToBoolean(ComparisonExpression.java:78) ~[freemarker-2.3.30.jar!/:2.3.30]
	at freemarker.core.ParentheticalExpression.evalToBoolean(ParentheticalExpression.java:35) ~[freemarker-2.3.30.jar!/:2.3.30]
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48) ~[freemarker-2.3.30.jar!/:2.3.30]
	at freemarker.core.Environment.visit(Environment.java:334) ~[freemarker-2.3.30.jar!/:2.3.30]
	at freemarker.core.Environment.visit(Environment.java:340) ~[freemarker-2.3.30.jar!/:2.3.30]
	at freemarker.core.Environment.process(Environment.java:313) ~[freemarker-2.3.30.jar!/:2.3.30]
	at freemarker.template.Template.process(Template.java:383) ~[freemarker-2.3.30.jar!/:2.3.30]
	at org.springframework.ui.freemarker.FreeMarkerTemplateUtils.processTemplateIntoString(FreeMarkerTemplateUtils.java:50) ~[spring-context-support-5.3.1.jar!/:5.3.1]
	at com.zebrunner.ms.service.impl.TemplateServiceImpl.processIntoHtml(TemplateServiceImpl.java:57) ~[classes!/:na]
```

**Comment by vdelendik** [comment]
fixed in develop branch

**Comment by dhreben** [comment]
Fixed.
<img width="1157" alt="Screenshot 2021-02-05 at 16 13 07" src="https://user-images.githubusercontent.com/50950954/107038063-0aad0580-67cd-11eb-8c82-be57650be08a.png">
